name: morse_module
description: Quickly and safely try out other people's editor setups
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.6.0
  yaml: ^2.2.1
  console: ^3.1.0
  meta: ^1.1.8
  process_run: ^0.10.9

dev_dependencies:
  import_sorter: ^2.0.1

  pedantic: ^1.8.0
  test: ^1.6.0

import_sorter:
  emojis: true
